### ISSUE TITLE
Textures not being rendered correctly on Epoch assets

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#42]
I'm sure you know but, since the latest update, the textures are not being rendered correctly on Epoch items. E.g chainsaw, cinder blocks.

Cheers,
Grahame

**Comment by morgoth0** [comment]
![20170824133845_1](https://user-images.githubusercontent.com/16226987/29680215-e4231ca2-88d1-11e7-885f-df21caca2ea1.jpg)

Example of the chainsaw

**Comment by ravmustang** [comment]
was fixed with todays update.
