### ISSUE TITLE
Crafting workbench crashes ARMA3 in Experimental

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#43]
As the title says, when attempting to craft a workbench ARMA3 crashes to the desktop. Crafting lumber packs is fine. Will test other craftables. Assume it's related to the config issues on texture rendering.

Cheers,
Grahame.

**Comment by ravmustang** [comment]
Tested crafting menu and building of Workbench.
All does seem to be back to normal with todays assets_1 repack.
