### ISSUE TITLE
Cinder Garage Door with Hatch Kit?

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#50]
I love the new cinder door model... excellent. Was just wondering whether it should be a kit though or, like the other upgrades, simply be an upgrade to an existing cinder garage door as part of CfgBaseBuilding.hpp.

Cheers,
Grahame.

**Comment by vbawol** [comment]
I would say It can be both a kit and an in-place upgrade for full cinder wall.

**Comment by morgoth0** [comment]
That's fair enough, then I guess it's up to the server owners to decide which way to go. 

Cheers, 
Grahame
