### ISSUE TITLE
Error in stringtable name for Rice Box

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#55]
Hi,
Line 3028 in CfgMagazines.hpp should be changed from:

		displayName = "$STR_EPOCH_ItemRice";

to

		displayName = "$STR_EPOCH_ItemRiceBox";

And line 3030 should be changed from

		descriptionShort = "$STR_EPOCH_ItemRiceDesc";
 
to

		descriptionShort = "$STR_EPOCH_ItemRiceBoxDesc";

Cheers,
Grahame.

**Comment by vbawol** [comment]
Thanks @morgoth0 and @Ignatz-HeMan for the commit
