### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#61]
So, I'm looking to help add new things for 1.0 and I was wondering whether I'm getting the code right. Let's assume that I wanted to add a burn barrel that would initially be turned off on placement but could be lit and put out. Ignoring for the moment a basic build kit, crafting and the string table entries would this entry for CfgVehicles.hpp be correct and work?

`    class Fireplace_SIM_EPOCH : Constructions_modular_F
    {
        author = "Bohemia Interactive";
        scope = 2;
		model = "\A3\Structures_F\Items\Vessels\MetalBarrel_empty_F.p3d";
        displayName = "$STR_EPOCH_BurnBarrelSIM";
    };

	class Land_MetalBarrel_empty_F: Constructions_static_F
	{
		author = "Bohemia Interactive";
		mapSize = 0.62;
		scope = 2;
		displayName = "$STR_EPOCH_BurnBarrel";
		model = "\A3\Structures_F\Items\Vessels\MetalBarrel_empty_F.p3d";
		vehicleClass = "Epoch_objects";
		destrType = "DestructEngine";
		simulation = "fire";
		keepHorizontalPlacement = 0;
		class Effects: SmallFire
		{
			class Light1
			{
				simulation = "light";
				type = "SmallFireLight";
			};
			class sound
			{
				simulation = "sound";
				type = "Fire";
			};
			class Smoke1
			{
				simulation = "particles";
				type = "SmallFireS";
			};
			class Fire1: Smoke1
			{
				simulation = "particles";
				type = "SmallFireBarrel";
			};
			class Refract1
			{
				simulation = "particles";
				type = "Refract";
			};
		};
	};`

One other question re the config, in class Effects, it inherits from SmallFire. The Epoch camp fire does not, so should the inheritance be removed?

Cheers,
Grahame.

**Comment by ravmustang** [comment]
Check out my DonkeyPunch Build Everything Arma.
Its made for all modes and mods of arma 3.
It has direct compatibility for Epoch and all 2k+ more like 2500 can be ported in very easily.
There are magazines, vehicles, itemInteractions, and more configured already.
If any crafting is wanted just add that in!

We already had a quick discussion a few months ago about this and we were going to do it in sections as needed. Check if new model is needed or go ahead with arma asset.

If you would like to jump in on this by all means cmon in. Present your batch of additions, keep it short for ease of review and approval, and let's get em in!!!!

Rock on Grahame! 😜

**Comment by vbawol** [comment]
This is how you make it lit from the start.
```
class EventHandlers
        {
            init = "(_this select 0) inflame true";
        };
```



and this is the config for smallFire, you can either merge it with Effects or add this to the main configs alongside CfgVehicles, etc.
```
class SmallFire
{
	class Light1
	{
		simulation="light";
		type="SmallFireLight";
	};
	class sound
	{
		simulation="sound";
		type="Fire";
	};
	class Fire1
	{
		simulation="particles";
		type="SmallFireF";
	};
	class Refract1
	{
		simulation="particles";
		type="SmallFireFRefract";
	};
	class Smoke1
	{
		simulation="particles";
		type="SmallFireS";
	};
};
```
OR simply add this before cfgVehicles to inherit it from the configs, 
```
class SmallFire;
class CfgVehicles
{
...
};
```

**Comment by morgoth0** [comment]
I'm looking at the DPBEA... looks sweet and covers everything I need. Just got to edit my server(s) CfgCrafting and CfgBaseBuilding with the entries in the mod support folder that I want on them, play with the recipes to suit my server(s) and boom, done. 

Wondering whether there would still be a reason for adding some certain items to core Epoch though for those that want to keep things pretty vanilla. Just talking about items already available in A2/Epoch - like the example of burn barrels? Thoughts?

**Comment by vbawol** [comment]
Sure @morgoth0, I think it is a good idea to try to have parity with A2 Epoch in terms of base building objects.
