### ISSUE TITLE
Am I doing things right here

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#68]
Before I update any files or make any changes I thought I would ask you folks whether I'm doing this right. My aim for 1.0 is to pass back the building items from A2/Epoch so that they, building kits (and mission configs) are all ready to go. 

Here are what I think I need for the CfgVehicles models covering Burn Barrels, Camo Nets and a Light Pole. Can you let me know whether I've done these right or not. 

`
    class BurnBarrel_SIM_EPOCH : Constructions_modular_F
    {
        author = "BI";
        scope = 2;
		model = "\A3\Structures_F\Items\Vessels\MetalBarrel_empty_F.p3d";
        displayName = "$STR_EPOCH_BurnBarrel";
    };

    class BurnBarrel_EPOCH : Constructions_static_F
    {
        author = "BI";
		mapSize = 0.62;
        scope = 2;
		model = "\A3\Structures_F\Items\Vessels\MetalBarrel_empty_F.p3d";
        displayName = "$STR_EPOCH_BurnBarrel";
		vehicleClass = "Epoch_objects";
		destrType = "DestructEngine";
		simulation = "fire";
		keepHorizontalPlacement = 0;
		class Effects
		{
			class Light1
			{
				simulation = "light";
				type = "SmallFireLight";
			};
			class sound
			{
				simulation = "sound";
				type = "Fire";
			};
			class Smoke1
			{
				simulation = "particles";
				type = "SmallFireS";
			};
			class Fire1: Smoke1
			{
				simulation = "particles";
				type = "SmallFireBarrel";
			};
			class Refract1
			{
				simulation = "particles";
				type = "Refract";
			};
		};
    };	
	
    class LightPole_SIM_EPOCH : Constructions_modular_F
    {
        author = "BI";
        scope = 2;
		model = "\A3\Structures_F\Civ\Lamps\LampShabby_F.p3d";
        displayName = "$STR_EPOCH_LightPole";
    };

    class LightPole_EPOCH : Constructions_static_F
    {
        author = "BI";
		mapSize = 0.79;
        scope = 2;
		model = "\A3\Structures_F\Civ\Lamps\LampShabby_F.p3d";
        displayName = "$STR_EPOCH_LightPole";
		vehicleClass = "Epoch_objects";
		destrType = "DestructTree";
		armor = 200;
		class Reflectors
		{
			class Light_1
			{
				color[] = {1100,700,500};
				ambient[] = {11,7,5};
				intensity = 5;
				size = 1;
				innerAngle = 80;
				outerAngle = 130;
				coneFadeCoef = 3;
				position = "Light_1_pos";
				direction = "Light_1_dir";
				hitpoint = "Light_1_hitpoint";
				selection = "Light_1_hide";
				useFlare = 1;
				flareSize = 0.9;
				flareMaxDistance = 100;
				class Attenuation
				{
					start = 0;
					constant = 0;
					linear = 0;
					quadratic = 0.8;
					hardLimitStart = 30;
					hardLimitEnd = 40;
				};
			};
		};
    };	
	
    class SmallForestCamoNet_SIM_EPOCH : Constructions_modular_F
    {
        author = "BI";
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_F.p3d";
        displayName = "$STR_EPOCH_SmallForestCamoNet";
    };

    class SmallForestCamoNet_EPOCH : Constructions_static_F
    {
        author = "BI";
		mapSize = 14.59;
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_F.p3d";
        displayName = "$STR_EPOCH_SmallForestCamoNet";
		vehicleClass = "Epoch_objects";
		destrType = "DestructTent";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_BLUFOR_CA.paa"};
		hiddenSelectionsMaterials[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_BLUFOR.rvmat"};
    };	
	
    class SmallDesertCamoNet_SIM_EPOCH : Constructions_modular_F
    {
        author = "BI";
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_F.p3d";
        displayName = "$STR_EPOCH_SmallDesertCamoNet";
    };

    class SmallDesertCamoNet_EPOCH : Constructions_static_F
    {
        author = "BI";
		mapSize = 14.59;
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_F.p3d";
        displayName = "$STR_EPOCH_SmallDesertCamoNet";
		vehicleClass = "Epoch_objects";
		destrType = "DestructTent";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_OPFOR_CA.paa"};
		hiddenSelectionsMaterials[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_BLUFOR.rvmat"};
    };	
	
    class LargeForestCamoNet_SIM_EPOCH : Constructions_modular_F
    {
        author = "BI";
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_Big_F.p3d";
        displayName = "$STR_EPOCH_LargeForestCamoNet";
    };

    class LargeForestCamoNet_EPOCH : Constructions_static_F
    {
        author = "BI";
		mapSize = 19.32;
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_Big_F.p3d";
        displayName = "$STR_EPOCH_LargeForestCamoNet";
		vehicleClass = "Epoch_objects";
		destrType = "DestructTent";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_BLUFOR_CA.paa"};
		hiddenSelectionsMaterials[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_BLUFOR.rvmat"};
    };	
	
    class LargeDesertCamoNet_SIM_EPOCH : Constructions_modular_F
    {
        author = "BI";
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_Big_F.p3d";
        displayName = "$STR_EPOCH_LargeDesertCamoNet";
    };

    class LargeDesertCamoNet_EPOCH : Constructions_static_F
    {
        author = "BI";
		mapSize = 14.59;
        scope = 2;
		model = "\A3\Structures_F\Mil\Shelters\CamoNet_Big_F.p3d";
        displayName = "$STR_EPOCH_LargeDesertCamoNet";
		vehicleClass = "Epoch_objects";
		destrType = "DestructTent";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_OPFOR_CA.paa"};
		hiddenSelectionsMaterials[] = {"\A3\Structures_F\Mil\Shelters\Data\CamoNet_BLUFOR.rvmat"};
    };	
	
`
I have the configs for an outhouse (Land_FieldToilet_F), single and double portable lights, sandbag walls and a small bunker, a fuel pump, sun shade, bench (Land_Bench_05_F), tower (Land_Lifeguard_Tower_01_F), Scaffolding and a sink (plus a couple of other things). This covers all the A2/Epoch buildables that I can remember.

If this code is cool then I will start updating the files in my repo and push back.

Cheers,
Grahame.

**Comment by morgoth0** [comment]
Actually one thing I noticed after posting is I could have the camo tents inherit from the previous entries, to keep things cleaner (obviously with different textures) as BI does it, so long as the base class inherits from Constructions_modular_F and Constructions_static_F

**Comment by ravmustang** [comment]
Camo nets are rough, please test them and make sure you can access them after build, otherwise no one will be able to move it / remove it / nor delete by admin if we cant see the model as cursorObject or cursorTarget.

Its a known issue with the camo nets and barbed wire, which is why @Helion4 had made the wire fence for Epoch not too long ago.

Keep us in the loop if they(camo nets) work or still present the same issue.

Inherits are great!

**Comment by morgoth0** [comment]
Camo Nets had the same problem in A2/Epoch too so it would be pretty similar ;) I will however test and report back on those. But the basics of the definitions - for example the lightpole and burn barrel. Are they okay?

**Comment by morgoth0** [comment]
Oh, one thing to note is that I actually have tested building all of these (including the ones listed as being in progress), just not using Epoch's CfgVehicles.hpp/CfgMagazines.hpp. So I'm more asking about the class definitions posted. 

I hacked 0.5's base building/maintenance code and the interactions related configs/code so people can build them without the interim step of having a kit. So, yes, getting a cursor target on the camo nets is almost impossible but I will check on admin deletes and let folks know. All the other props build perfectly and operate as any other base prop.

Cheers again,
Grahame.

**Comment by ravmustang** [comment]
Hey just checking back.
Yeah the burn barrel looks good.
I always will suggest to dump the config with inherits for that object you wish to port in
You can always remove lines that will have no impact

Will this barrel always be burning? or are ya bringing in the empty so we can have some actions for turning it on and off as to not overdue the servers with burning barrels at every restart.

**Comment by morgoth0** [comment]
Specifically the empty so that you have to relight it after a restart. It also looks better than the burning one tbh, since it has an open top

**Comment by ravmustang** [comment]
Thats my thought process yes.
It would be better to have to light them up.

You can use for the condition arma 3's inflamed function.
I also suggest adding a check for lighter_Epoch to light it up.
If the zippo doesnt have an ammo setup, we can make that happen and then remove 1 round every time they light stuff, maybe even have them refill it with lighter fluid with either crafting or mag repacking type function.

**Comment by morgoth0** [comment]
It would be good to have a reason for the lighter. Been thinking for a while about making crafting and interactions take a required item but give it back to you - for example, for upgrading campfires and other things to make those items more useful than just sellable loot. Would be nice to require a can opener for canned food, then return it too (but that's actually easy to set up assuming that you can return more than one item that, iirc, you cannot...).

The idea of rounds is cool. Would also like to see the canteen be able to be used, say four times, and then need refilling but magazines with ammo configs are not something that I am currently familiar with

**Comment by ravmustang** [comment]
Having a quick look at this for ya.

This should work just fine

```class EventHandlers
			{
				init = "(_this select 0) inflame false";
			};
			class UserActions
			{
				class FlameON
				{
					displayNameDefault = ""; // can add fire icon here
					displayName = "Light Fire";
					position = "";
					priority = 11;
					radius = 1.5;
					aiMaxRange = "1 * 3";
					onlyForPlayer = 0;
					condition = "!inflamed && ('lighter_epoch' in magazines player)";
					statement = "(_this select 0) inflame true";
				};
				class FlameOFF
				{
					displayNameDefault = "";
					displayName = "Put Out Fire";
					position = "";
					priority = 11;
					radius = 1.5;
					aiMaxRange = "1 * 3";
					onlyForPlayer = 0;
					condition = "inflamed";
					statement = "(_this select 0) inflame true";
				};
			}```

**Comment by morgoth0** [comment]
Cheers. Will test it on my dev experimental server in the morning along with all the other models and configs. Should be able to get all this stuff in a push in the morning

**Comment by ravmustang** [comment]
correction made above to the FlameOFF statement

**Comment by morgoth0** [comment]
LOL, yes :)

**Comment by morgoth0** [comment]
Will fix the misdefinition in the Watch Tower and get a pull request in: https://www.youtube.com/watch?v=dRDhCQxpfr0
