### ISSUE TITLE
Please, please, please can we have a morphine injector?

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#69]
Pretty please if it is not too much work for the modeling folks? Maybe a red Adrenaline injector??? The reason I ask is that I've already done a fair bit of work on some (optional?) additions to the Epoch medical system that include usable bandages (only stop bleeding), FAKs (if flag set then work in the same way as vehicle repair parts and just heal a bit of damage), blood bags (self-blood bag, blood bag others and fill blood bags) and I would like to add morphine as something that heals leg damage (and thus removes the broken leg icon as well)...

Assuming like Advanced Vehicle Repair that this would be a config option in CfgEpochClient.hpp with the default being false.

Cheers again,
Grahame

**Comment by Helion4** [comment]
![864837c13d38efc419c876e0180a9840](https://user-images.githubusercontent.com/29925182/31152448-0872d7dc-a894-11e7-8c96-609323274f05.png)

**Comment by morgoth0** [comment]
I love you... in a completely normal way of course!!! 

Cheers very much!

**Comment by morgoth0** [comment]
I also **LOVE** Morphine... in a non-completely normal way (in ARMA)... you would have to have been there... was a meme for a while

**Comment by morgoth0** [comment]
The good news is I can now work fully on my medical stuff for Epoch fully. Everything client side is in place so will be developing on my servers for a hotfix or 1.1 :)

**Comment by KRDucky** [comment]
Wow, sounds like you are requesting all the medical stuff from ACE3 mod. Morphine, Bandages, Bloodbags, Epi-pens, Atropine, Saline, Plasma, etc.

**Comment by KRDucky** [comment]
not entirely sure why you dont just fully integrate ACE3 into Epoch. At this point.

**Comment by morgoth0** [comment]
Character models... and hit locations actually. But looking more at a A2/DayZ/Epoch model rather than ACE3 (which will obviously be optional, but morphine was the last client side component needed)

**Comment by KRDucky** [comment]
Wish there was a 1 or 0 switch I can throw in settings that if I load with ACE3, it already has the necessary stuff running. AKA, Want ACE3? put a 1 here and load with ACE3. ^_^

**Comment by morgoth0** [comment]
Unfortunately not... ACE3 works (with code mods to Epoch to turn off and modify how _it_ handles and uses damage) but not seamlessly. However, what I am working on will provide the A2/Epoch feel for medical which tbh, in Epoch, is all I really want
