### ISSUE TITLE
Item Names are Classnames

### ISSUE THREAD

**Issue by RZSenfo** [EpochModTeam/EpochCore#83]
https://github.com/EpochModTeam/EpochCore/blob/45684ea498852e024ac6860cef9ce76114401dc0/Sources/a3_epoch_configs/Configs/CfgMagazines.hpp#L2841

**Comment by RZSenfo** [comment]
https://github.com/EpochModTeam/EpochCore/blob/45684ea498852e024ac6860cef9ce76114401dc0/Sources/a3_epoch_configs/Configs/CfgMagazines.hpp#L2865

**Comment by Ignatz-HeMan** [comment]
You are right. 
Would you create a PR?

**Comment by RZSenfo** [comment]
will do it this afternoon

**Comment by vbawol** [comment]
Thanks for the PR #85
