### ISSUE TITLE
Issue with the UAV brain FSM?

### ISSUE THREAD

**Issue by morgoth0** [EpochModTeam/EpochCore#90]
Hmm... could be a logical problem in the drone code ... In the fsm for the drone it has this: 

                         "[[(getPos _trgt),80,150,1,true] call EPOCH_fnc_findSafePos,_copter] call EPOCH_supportCopter;" \n

but that means that EPOCH_supportCopter will call EPOCH_unitSpawn.sqf with a randomized location from the targeted player  ... but then the spawn code randomizes it with 

            _pos = [_targetPos,80,150,1,true] call EPOCH_fnc_findSafePos;

potentially spawning the enemy AI on the player's location... or am I going mad?

Shouldn't EPOCH_supportCopter.sqf be called just with the player's pos? I.e. I think the FSM code should just be: 
                         "[getPos _trgt,_copter] call EPOCH_supportCopter;" \n

Cheers,
Grahame.

**Comment by ravmustang** [comment]
Looks like unitSpawn is only randomizing position if the variable is an empty array.

 if (_pos isEqualTo []) then {
            _pos = [_targetPos,80,150,1,true] call EPOCH_fnc_findSafePos;
        };

**Comment by morgoth0** [comment]
FFS... I am an idiot! Thanks Sanchez, much appreciated!

**Comment by ravmustang** [comment]
Tis ok kind sir!
Keep looking and suggesting,  it will make EPOCH better in the long run
